FROM node:20

WORKDIR /patient-registration-server
COPY package.json .
RUN npm install
COPY . .

ARG REACT_APP_API_BASE_URL
ENV REACT_APP_API_BASE_URL=$REACT_APP_API_BASE_URL

RUN npm run build

EXPOSE 8080

CMD [ "npm", "run", "preview" ]